// SPDX-License-Identifier: GPL-3.0-or-later

package ha

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateKeepalivedConf_Primary(t *testing.T) {
	got, err := GenerateKeepalivedConf(KeepalivedParams{
		Role:      RolePrimary,
		Interface: "eth0",
		VIP:       "192.168.1.100",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	want := `! keepalived.conf generated by HydraDNS
! Active-passive VRRP failover of the virtual IP ONLY.
! HydraDNS application state is NOT shared or replicated between nodes.
vrrp_instance VI_HYDRA {
    state MASTER
    interface eth0
    virtual_router_id 51
    priority 200
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass hydradns
    }
    virtual_ipaddress {
        192.168.1.100
    }
}
`
	if got != want {
		t.Fatalf("primary config mismatch\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestGenerateKeepalivedConf_Backup(t *testing.T) {
	got, err := GenerateKeepalivedConf(KeepalivedParams{
		Role:      RoleBackup,
		Interface: "eth0",
		VIP:       "192.168.1.100",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	want := `! keepalived.conf generated by HydraDNS
! Active-passive VRRP failover of the virtual IP ONLY.
! HydraDNS application state is NOT shared or replicated between nodes.
vrrp_instance VI_HYDRA {
    state BACKUP
    interface eth0
    virtual_router_id 51
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass hydradns
    }
    virtual_ipaddress {
        192.168.1.100
    }
}
`
	if got != want {
		t.Fatalf("backup config mismatch\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestGenerateKeepalivedConf_OverridesApplied(t *testing.T) {
	got, err := GenerateKeepalivedConf(KeepalivedParams{
		Role:         RolePrimary,
		Interface:    "ens160",
		VIP:          "10.10.0.5/24",
		InstanceName: "VI_EDGE",
		RouterID:     77,
		AdvertInt:    2,
		AuthPass:     "s3cret",
		Priority:     150,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	for _, want := range []string{
		"vrrp_instance VI_EDGE {",
		"state MASTER",
		"interface ens160",
		"virtual_router_id 77",
		"priority 150",
		"advert_int 2",
		"auth_pass s3cret",
		"10.10.0.5/24",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("generated config missing %q\n%s", want, got)
		}
	}
}

func TestGenerateKeepalivedConf_Validation(t *testing.T) {
	cases := []struct {
		name string
		p    KeepalivedParams
	}{
		{"invalid role", KeepalivedParams{Role: Role("leader"), Interface: "eth0", VIP: "1.1.1.1"}},
		{"missing interface", KeepalivedParams{Role: RolePrimary, VIP: "1.1.1.1"}},
		{"missing vip", KeepalivedParams{Role: RolePrimary, Interface: "eth0"}},
		{"router id too high", KeepalivedParams{Role: RolePrimary, Interface: "eth0", VIP: "1.1.1.1", RouterID: 300}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := GenerateKeepalivedConf(tc.p); err == nil {
				t.Fatalf("expected error for %s, got nil", tc.name)
			}
		})
	}
}

func TestWriteKeepalivedConf(t *testing.T) {
	path := filepath.Join(t.TempDir(), "keepalived.conf")
	p := KeepalivedParams{Role: RoleBackup, Interface: "eth0", VIP: "192.168.1.100"}

	if err := WriteKeepalivedConf(p, path); err != nil {
		t.Fatalf("WriteKeepalivedConf: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read written file: %v", err)
	}
	want, err := GenerateKeepalivedConf(p)
	if err != nil {
		t.Fatalf("GenerateKeepalivedConf: %v", err)
	}
	if string(data) != want {
		t.Fatalf("written file content mismatch\n--- file ---\n%s\n--- want ---\n%s", data, want)
	}
}
