// SPDX-License-Identifier: GPL-3.0-or-later

package ha

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"text/template"
)

// Keepalived generator defaults.
const (
	DefaultInstanceName   = "VI_HYDRA"
	DefaultRouterID       = 51
	DefaultAdvertInt      = 1
	DefaultAuthPass       = "hydradns"
	DefaultPriorityMaster = 200
	DefaultPriorityBackup = 100
)

// KeepalivedParams describes the inputs needed to render a keepalived.conf for
// active-passive VRRP failover of the virtual IP.
type KeepalivedParams struct {
	// Role selects MASTER (primary) vs BACKUP (backup) and the default priority.
	Role Role
	// Interface is the network interface VRRP binds to (e.g. "eth0"). Required.
	Interface string
	// VIP is the virtual IP address, optionally with a CIDR suffix
	// (e.g. "192.168.1.100" or "192.168.1.100/24"). Required.
	VIP string
	// InstanceName is the vrrp_instance name. Defaults to DefaultInstanceName.
	InstanceName string
	// RouterID is virtual_router_id (0-255). Both nodes in a pair must match.
	// Defaults to DefaultRouterID.
	RouterID int
	// AdvertInt is the VRRP advertisement interval in seconds. Defaults to 1.
	AdvertInt int
	// AuthPass is the shared VRRP authentication password. Defaults to
	// DefaultAuthPass. Both nodes must match.
	AuthPass string
	// Priority overrides the VRRP priority. When 0, a role-appropriate default
	// is used (primary high, backup low).
	Priority int
}

// keepalivedView is the concrete, defaulted view handed to the template.
type keepalivedView struct {
	InstanceName string
	VRRPState    string
	Interface    string
	RouterID     int
	Priority     int
	AdvertInt    int
	AuthPass     string
	VIP          string
}

var keepalivedTmpl = template.Must(template.New("keepalived").Parse(
	`! keepalived.conf generated by HydraDNS
! Active-passive VRRP failover of the virtual IP ONLY.
! HydraDNS application state is NOT shared or replicated between nodes.
vrrp_instance {{.InstanceName}} {
    state {{.VRRPState}}
    interface {{.Interface}}
    virtual_router_id {{.RouterID}}
    priority {{.Priority}}
    advert_int {{.AdvertInt}}
    authentication {
        auth_type PASS
        auth_pass {{.AuthPass}}
    }
    virtual_ipaddress {
        {{.VIP}}
    }
}
`))

// resolve applies defaults and validates the params, returning a render view.
func (p KeepalivedParams) resolve() (keepalivedView, error) {
	var vrrpState string
	defaultPriority := 0
	switch p.Role {
	case RolePrimary:
		vrrpState = "MASTER"
		defaultPriority = DefaultPriorityMaster
	case RoleBackup:
		vrrpState = "BACKUP"
		defaultPriority = DefaultPriorityBackup
	default:
		return keepalivedView{}, fmt.Errorf("ha: invalid role %q (want primary or backup)", p.Role)
	}

	if strings.TrimSpace(p.Interface) == "" {
		return keepalivedView{}, fmt.Errorf("ha: keepalived interface is required")
	}
	if strings.TrimSpace(p.VIP) == "" {
		return keepalivedView{}, fmt.Errorf("ha: keepalived VIP is required")
	}

	v := keepalivedView{
		InstanceName: p.InstanceName,
		VRRPState:    vrrpState,
		Interface:    strings.TrimSpace(p.Interface),
		RouterID:     p.RouterID,
		Priority:     p.Priority,
		AdvertInt:    p.AdvertInt,
		AuthPass:     p.AuthPass,
		VIP:          strings.TrimSpace(p.VIP),
	}
	if v.InstanceName == "" {
		v.InstanceName = DefaultInstanceName
	}
	if v.RouterID == 0 {
		v.RouterID = DefaultRouterID
	}
	if v.RouterID < 0 || v.RouterID > 255 {
		return keepalivedView{}, fmt.Errorf("ha: router id %d out of range (0-255)", v.RouterID)
	}
	if v.AdvertInt == 0 {
		v.AdvertInt = DefaultAdvertInt
	}
	if v.AuthPass == "" {
		v.AuthPass = DefaultAuthPass
	}
	if v.Priority == 0 {
		v.Priority = defaultPriority
	}
	return v, nil
}

// GenerateKeepalivedConf renders a keepalived.conf for active-passive VRRP
// failover from the given params, applying defaults for omitted fields.
func GenerateKeepalivedConf(p KeepalivedParams) (string, error) {
	v, err := p.resolve()
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := keepalivedTmpl.Execute(&buf, v); err != nil {
		return "", fmt.Errorf("ha: render keepalived.conf: %w", err)
	}
	return buf.String(), nil
}

// WriteKeepalivedConf renders the config and writes it to path (0600:
// the file can carry the VRRP auth password and keepalived reads it as root).
func WriteKeepalivedConf(p KeepalivedParams, path string) error {
	conf, err := GenerateKeepalivedConf(p)
	if err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(conf), 0o600); err != nil {
		return fmt.Errorf("ha: write keepalived.conf to %s: %w", path, err)
	}
	return nil
}
