name: 📖 Documentation
description: Suggest improvements or report issues with documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! 📖
        
        Good documentation makes PhantomCore more accessible to everyone.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - README
        - Setup/Installation Guide
        - Configuration Guide
        - API Documentation
        - Contributing Guidelines
        - Code Comments
        - Examples/Tutorials
        - Architecture Documentation
        - Troubleshooting Guide
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Documentation Issue
      description: What's wrong or missing in the current documentation?
      placeholder: |
        The current documentation is unclear about...
        Missing information on how to...
        The example doesn't work because...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: |
        Add a section explaining...
        Include an example showing...
        Clarify the steps for...
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is this documentation located? (file path, URL, etc.)
      placeholder: "e.g., README.md, docs/setup.md, website section"

  - type: textarea
    id: audience
    attributes:
      label: Target Audience
      description: Who would benefit from this documentation improvement?
      placeholder: |
        - New users trying to set up PhantomCore
        - Developers contributing to the project
        - System administrators deploying in production
        - etc.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that would help improve the documentation
      placeholder: Links to good examples, specific use cases, etc.