name: ✨ Feature Request
description: Suggest a new feature or enhancement for PhantomCore
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! ✨
        
        Please help us understand your use case and proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this feature solve? What's your use case?
      placeholder: |
        I'm always frustrated when...
        As a user, I need to...
        Currently there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: |
        I would like PhantomCore to...
        The feature should work by...
        Users would interact with it by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        Alternative 1: ...
        Alternative 2: ...
        Why the proposed solution is better: ...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of PhantomCore would this feature affect?
      options:
        - DNS Engine
        - Policy Engine
        - Configuration
        - Storage/Database
        - Monitoring/Logging
        - Docker/Deployment
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low (small changes)
        - Medium (moderate changes)
        - High (significant changes)
        - Unknown

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature introduce breaking changes?
      options:
        - label: This feature might introduce breaking changes
        - label: This feature is backwards compatible

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas for how this could be implemented?
      placeholder: |
        - Add new configuration option...
        - Modify the DNS handler to...
        - Create new API endpoint...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Links to similar features in other projects, mockups, etc.